/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Chris Bellis, Chris Perry
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package cite_graph;

import javax.servlet.GenericServlet;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebServlet;
import java.io.IOException;

/**
 * Created by Chris on 7/16/15.
 * <p>
 * A servlet that serves up a new randomized JSONObject each time you use it!
 */
@WebServlet(value = "/json", name = "randomJSON")
public class JSONGeneratorServlet extends GenericServlet {

    /**
     * Prints to screen the contents of the random JSONObject generated by the JSONGenerator
     *
     * @param req the servlet request
     * @param res the servlet response
     * @throws ServletException if something goes wrong with the request/response
     * @throws IOException      if something goes wrong with writing the response
     */
    @Override
    public void service(ServletRequest req, ServletResponse res) throws ServletException, IOException {
        // Print a random JSONObject generated by the patented JSONGenerator.
        res.getWriter().println(jsonGenerator.getRandomJSON());
    }

}
